services:
  asere-food-api:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "0.0.0.0:4001:4001"

    environment:
        APP_PORT: $APP_PORT
        UI_URL: $UI_URL
        EMAIL_CONFIRMATION_URL: $EMAIL_CONFIRMATION_URL
        EMAIL_RESET_PASSWORD_URL: $EMAIL_RESET_PASSWORD_URL

        TROPIPAY_URL_SUCCESS: $TROPIPAY_URL_SUCCESS
        TROPIPAY_URL_FAILURE: $TROPIPAY_URL_FAILURE
        TROPIPAY_URL_NOTIFICATION: $TROPIPAY_URL_NOTIFICATION

        MAX_HOURS_TO_AUTO_CANCEL_ORDER: $MAX_HOURS_TO_AUTO_CANCEL_ORDER
        MAX_HOURS_TO_DELETE_SHOPPING_CART: $MAX_HOURS_TO_DELETE_SHOPPING_CART

        NODE_ENV: $NODE_ENV
        SWAGGER_PASSWORD: $SWAGGER_PASSWORD
        
        SECRET_KEY: $SECRET_KEY
        SEED_ADMIN_EMAIL: $SEED_ADMIN_EMAIL
        SEED_ADMIN_PASSWORD: $SEED_ADMIN_PASSWORD
        TROPIPAY_CLIENT_ID: $TROPIPAY_CLIENT_ID
        TROPIPAY_CLIENT_SECRET: $TROPIPAY_CLIENT_SECRET
        
        MAIL_HOST: $MAIL_HOST
        MAIL_PORT: $MAIL_PORT
        MAIL_USER: $MAIL_USER
        MAIL_PASSWORD: $MAIL_PASSWORD
        MAIL_SECURE: $MAIL_SECURE
        SENDER_EMAIL: $SENDER_EMAIL
        SENDER_NAME: $SENDER_NAME
        
        DB_HOST: $DB_HOST
        DB_PORT: $DB_PORT
        DB_DATABASE: $DB_DATABASE
        DB_USERNAME: $DB_USERNAME
        DB_PASSWORD: $DB_PASSWORD

        MINIO_ENDPOINT: $MINIO_ENDPOINT
        MINIO_PORT: $MINIO_PORT
        MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
        MINIO_SECRET_KEY: $MINIO_SECRET_KEY
        MINIO_USE_SSL: $MINIO_USE_SSL
        MINIO_BUCKET_NAME: $MINIO_BUCKET_NAME

    networks:
      - asere-food

networks:
  asere-food: 
    external: true