services:
  asere-food-api:
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - "0.0.0.0:4001:4001"

    environment:
        APP_PORT: 4001
        UI_URL: https://asere-food.com
        EMAIL_CONFIRMATION_URL: https://asere-food.com/auth/verifyEmail
        EMAIL_RESET_PASSWORD_URL: https://asere-food.com/auth/resetPassword

        TROPIPAY_URL_SUCCESS: https://asere-food.com/payment/success
        TROPIPAY_URL_FAILURE: https://asere-food.com/payment/failure
        TROPIPAY_URL_NOTIFICATION: https://asere-food-api.mdialityc.com/v1/payments/charging

        MAX_HOURS_TO_AUTO_CANCEL_ORDER: 48
        MAX_HOURS_TO_DELETE_SHOPPING_CART: 24

        NODE_ENV: staging
        SWAGGER_PASSWORD: admin
        
        SECRET_KEY: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789JANDDAFOFAOINAIEEFAD
        SEED_ADMIN_EMAIL: admin@admin.admin
        SEED_ADMIN_PASSWORD: Admin2024.
        TROPIPAY_CLIENT_ID: ABC
        TROPIPAY_CLIENT_SECRET: ABC
        
        MAIL_HOST: smtp.gmail.com
        MAIL_PORT: 587
        MAIL_USER: eduardoglez64377@gmail.com
        MAIL_PASSWORD: pnei wfzu bbwb ufsz
        MAIL_SECURE: false
        SENDER_EMAIL: asere-food@gmail.com
        SENDER_NAME: Asere Food Admin
        
        DB_HOST: aws-0-us-east-1.pooler.supabase.com
        DB_PORT: 5432
        DB_DATABASE: asere-food-db
        DB_USERNAME: postgres.giewupmqqrcnrdillwax
        DB_PASSWORD: fCXko33My1bFAkKX

    networks:
      - asere-food

networks:
  asere-food: 
    external: true