import * as Joi from 'joi';

export const configSchema = Joi.object({
  APP_PORT: Joi.number().default(4001).required(),
  SECRET_KEY: Joi.string().required(),
  SEED_ADMIN_EMAIL: Joi.string().required(),
  SEED_ADMIN_PASSWORD: Joi.string().required(),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().required(),
  DB_DATABASE: Joi.string().required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_USER: Joi.string().email().required(),
  MAIL_PASSWORD: Joi.string().required(),
  MAIL_SECURE: Joi.boolean().required(),
  SENDER_EMAIL: Joi.string().email().required(),
  SENDER_NAME: Joi.string().required(),
  UI_URL: Joi.string().uri().required(),
  EMAIL_CONFIRMATION_URL: Joi.string().uri().required(),
  EMAIL_RESET_PASSWORD_URL: Joi.string().uri().required(),
  MAX_HOURS_TO_AUTO_CANCEL_ORDER: Joi.number().min(0).required(),
  MAX_HOURS_TO_DELETE_SHOPPING_CART: Joi.number().min(0).required(),
  TROPIPAY_URL_SUCCESS: Joi.string().uri().required(),
  TROPIPAY_URL_FAILURE: Joi.string().uri().required(),
  TROPIPAY_URL_NOTIFICATION: Joi.string().uri().required(),
  TROPIPAY_CLIENT_ID: Joi.string().required(),
  TROPIPAY_CLIENT_SECRET: Joi.string().required(),
  SWAGGER_PASSWORD: Joi.string().required(),
  NODE_ENV: Joi.string().required(),
  APP_URL: Joi.string().uri().required(),
  UPLOADS_PATH: Joi.string().optional(),
}).unknown();
