name: Deploy to Wonder CapRover

on:
  push:
    branches: ["production"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create appsettings.json from secret
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
          echo "UI_URL=${{ secrets.UI_URL }}" >> .env
          echo "EMAIL_CONFIRMATION_URL=${{ secrets.EMAIL_CONFIRMATION_URL }}" >> .env
          echo "EMAIL_RESET_PASSWORD_URL=${{ secrets.EMAIL_RESET_PASSWORD_URL }}" >> .env
          
          echo "TROPIPAY_URL_SUCCESS=${{ secrets.TROPIPAY_URL_SUCCESS }}" >> .env
          echo "TROPIPAY_URL_FAILURE=${{ secrets.TROPIPAY_URL_FAILURE }}" >> .env
          echo "TROPIPAY_URL_NOTIFICATION=${{ secrets.TROPIPAY_URL_NOTIFICATION }}" >> .env
          
          echo "MAX_HOURS_TO_AUTO_CANCEL_ORDER=${{ secrets.MAX_HOURS_TO_AUTO_CANCEL_ORDER }}" >> .env
          echo "MAX_HOURS_TO_DELETE_SHOPPING_CART=${{ secrets.MAX_HOURS_TO_DELETE_SHOPPING_CART }}" >> .env
          
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }}" >> .env
          
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "SEED_ADMIN_EMAIL=${{ secrets.SEED_ADMIN_EMAIL }}" >> .env
          echo "SEED_ADMIN_PASSWORD=${{ secrets.SEED_ADMIN_PASSWORD }}" >> .env
          echo "TROPIPAY_CLIENT_ID=${{ secrets.TROPIPAY_CLIENT_ID }}" >> .env
          echo "TROPIPAY_CLIENT_SECRET=${{ secrets.TROPIPAY_CLIENT_SECRET }}" >> .env
          
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_SECURE=${{ secrets.MAIL_SECURE }}" >> .env
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env
          echo "SENDER_NAME=${{ secrets.SENDER_NAME }}" >> .env
          
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          
          echo "MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}" >> .env
          echo "MINIO_PORT=${{ secrets.MINIO_PORT }}" >> .env
          echo "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> .env
          echo "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" >> .env
          echo "MINIO_USE_SSL=${{ secrets.MINIO_USE_SSL }}" >> .env
          echo "MINIO_BUCKET_NAME=${{ secrets.MINIO_BUCKET_NAME }}" >> .env

      - name: Create deploy.tar for CapRover
        run: tar --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='deploy.tar' -cvf deploy.tar .

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAP_ROVER_SERVER_MD }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN_CAP_ROVER }}"