name: deploy dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch: 

jobs:

  build:

    runs-on: etecsa-1

    steps:
    - uses: actions/checkout@v4

    - name: Add vars
      run: |
          echo "AUTH_ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" > .env
          echo "AUTH_ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> .env
          echo "AUTH_KEY=${{ secrets.AUTH_KEY }}" >> .env
          echo "CONNECTIONSTRINGS_POSTGRESQL_CONNECTION=${{ secrets.POSTGRES_CONNECTION_STRING }}" >> .env
          echo "LOGGING_LOGLEVEL_DEFAULT=${{ secrets.LOGGING_DEFAULT_LEVEL }}" >> .env
          echo "LOGGING_LOGLEVEL_MICROSOFT=${{ secrets.LOGGING_MICROSOFT_LEVEL }}" >> .env
    
    - name: Stop running container if exists
      run: |
          docker compose down || true

    - name: Clean up unused Docker resources
      run: |
          docker container prune --force
          docker image prune --force
          docker builder prune --force

    - name: Run Docker container        
      run: docker compose up -d --build
